CMakeLists.txt, README.md, README_CN.md, configure, examples/hello_world/src/hello_world.c, examples/switch_demo/src/tuya_config.h, tools/build_example.sh
=> support msys2

configure
=> adjust the configuration

platform/platform_config.yaml
=> Support [esp32s3]

README.md, README_zh.md, docs/en/tos_guide.md, docs/zh/tos_guide.md
=> update tos readme

platform/platform_config.yaml
=> esp32 fix: target empty

.gitignore, tools/multi_config_choice.sh, tos
1.config_choice support [board default config]
=> config_choice support [board default config]

platform/platform_config.yaml
1.Update platform: Ubuntu/LN882H/ESP32
=> update platform: Ubuntu/LN882H/ESP32

docs/en/tos_guide.md, docs/zh/tos_guide.md, platform/platform_config.yaml, tos
1.Update cmd [update/version]; 
2.Update Ubuntu commit
=> 1.update cmd [update/version]; 2.update Ubuntu commit

.github/workflows/check-build-apps.yml, tos
=> add github actions

boards/ESP32/DNESP32S3-BOX/DNESP32S3-BOX.c, boards/ESP32/DNESP32S3-BOX/board_config.h, boards/ESP32/common/audio/tdd_audio_atk_no_codec.c, boards/ESP32/common/audio/tdd_audio_atk_no_codec.h
=> fix: xl9555 setup

CMakeLists.txt, platform/platform_config.yaml, src/peripherals/audio_codecs/CMakeLists.txt, tools/kconfiglib/CMakeLists.txt, tools/kconfiglib/conf2cmake.py, tools/kconfiglib/conf2param.py, tools/kconfiglib/gen_build_param.cmake, tos
=> Param file

CMakeLists.txt, tools/cmake/util.cmake, tools/kconfiglib/CMakeLists.txt, tools/kconfiglib/conf2h.py
1.support open version in config.h
=> support open version in config.h

README.md, README_zh.md, tools/completion/tos.sh, tos
修复了通过tos set_example创建的/example目录下无法tos build的问题（使用pwd -P）
添加了bash和zsh自动补全的脚本
=> Fix build path and add shell completion

tools/cli_command/cli_build.py, tools/cli_command/cli_check.py, tools/cli_command/cli_update.py, tools/cli_command/util.py, tools/cli_command/util_git.py, tos.py
=> Feat tos update

.github/workflows/check-build-apps.yml, .gitignore, boards/T2/T2-U/Kconfig, tools/cli_command/cli_build.py, tools/cli_command/cli_check.py, tools/cli_command/cli_dev.py, tools/cli_command/util.py, tools/cli_command/util_files.py
1. support save product when “tos.py dev bac -d”
=> support bac -d save dist

export.sh, requirements.txt, tools/cli_command/cli_build.py, tools/cli_command/cli_check.py, tools/cli_command/cli_clean.py, tools/cli_command/cli_config.py, tools/cli_command/cli_dev.py, tools/cli_command/cli_update.py, tools/cli_command/cli_version.py, tools/cli_command/util.py, tools/cli_command/util_git.py, tos.py
1. support colour message;
2. support TAB complete tos.py;
=> Feat tos color tab

export.bat, export.ps1, export.sh, tools/cli_command/cli_build.py, tools/cli_command/util.py
1. prompt when platform commit change
=> prompt when platform commit change

.github/workflows/release.yml, tools/cli_command/cli_dev.py, tools/cli_command/cli_new.py, tools/cli_command/util.py
=> Feat release publish

src/peripherals/joystick/tdl_joystick/include/tdl_joystick_manage.h, src/peripherals/joystick/tdl_joystick/src/tdl_joystick_manage.c
=> fix joystick

apps/tuya_t5_pocket/tuya_t5_pocket_ai/src/game_pet.c
[Describe the PR content in detail here]
As part of this pull request, I've considered the following:
=> update get voice

apps/tuya_t5_pocket/tuya_t5_pocket_ai/src/display/ui/pet_area.c, apps/tuya_t5_pocket/tuya_t5_pocket_ai/src/game_pet.c
[Describe the PR content in detail here]
As part of this pull request, I've considered the following:
=> 1.fix pet voice; 2.pet show state

export.bat, export.ps1, export.sh, tools/cli_command/cli_flash.py, tools/cli_command/cli_new.py
[Describe the PR content in detail here]
As part of this pull request, I've considered the following:
=> Dev hello open

boards/T5AI/TUYA_T5AI_CORE/board_com_api.h
[Describe the PR content in detail here]
As part of this pull request, I've considered the following:
=> fix merge conflict

src/tuya_cloud_service/ble/ble_mgr.c
[在此详细描述 PR 的内容]/[Describe the PR content in detail here]
在本次拉取请求中，我已考虑以下事项 As part of this pull request, I've considered the following:
=> fix: free allocated memory in BLE event callback to prevent memory leaks

export.bat, export.ps1
[在此详细描述 PR 的内容]/[Describe the PR content in detail here]
在本次拉取请求中，我已考虑以下事项 As part of this pull request, I've considered the following:
=> fix: windows not found python3

platform/platform_config.yaml
[在此详细描述 PR 的内容]/[Describe the PR content in detail here]
在本次拉取请求中，我已考虑以下事项 As part of this pull request, I've considered the following:
=> fix t5ai: clean cmd
